### ISSUE TITLE
When using Crystalizer to analyze sink points, an error appears: "Java. io. FileNotFoundException:/root/SeriFuzzy/src/static/gadgetDB. store (No such file or directory)"

### ISSUE THREAD

**Issue by azure-z77** [HexHive/Crystallizer#2]
environment：
server：Ubuntu 22.04.2 LTS
Docker version 23.0.3, build 3e7cbfd

docker pull prashast94/crystallizer:latest 
docker run --security-opt seccomp=unconfined --name crystallize_test -v $PWD/targets:/root/SeriFuzz/targets -v $PWD/results:/root/SeriFuzz/results -it prashast94/crystallizer:latest /bin/bash
./run_campaigns.sh /root/SeriFuzz/targets/ngrinder/ngrinder-runtime-3.5.9.jar 60 60//error！!

details of errors as below:
== Java Exception in fuzzerInitialize:
Exception in thread "main" java.lang.NullPointerException
at com.example.GadgetDB.tagSourcesAndSinks(GadgetDB.java:114)
at com.example.SeriFuzz.fuzzerInitialize(SeriFuzz.java:129)

/root/SeriFuzz/jazzer
Restarting ./bazel-bin/jazzer --cp=./bazel-bin/examples/SeriFuzz_target_deploy.jar:/root/SeriFuzz/src/static/sootOutput/out.jar --target_class=com.example.SeriFuzz --instrumentation_excludes=org.jgrapht.::org.apache.log4j.::javassist.** --keep_going=5000 -timeout=60 -rss_limit_mb=8096
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

set -e
'[' '!' 2 -eq 2 ']'
OUTDIR=/root/SeriFuzz/results
MODE=concretization
'[' concretization = sinkID ']'
'[' concretization = concretization ']'
mkdir -p /root/SeriFuzz/results/concretization
cp -p /root/SeriFuzz/src/static/serifuzz.log /root/SeriFuzz/results/concretization/concretization_log
cp -p /root/SeriFuzz/src/static/fnIDList.store /root/SeriFuzz/results/concretization/
cp: cannot stat '/root/SeriFuzz/src/static/fnIDList.store': No such file or directory

notice:
ngrinder-runtime-3.5.9 is downloaded from https://mvnrepository.com/artifact/org.ngrinder/ngrinder-runtime

**Comment by CyanM0un** [comment]
I meet the same question, have any ideas?

**Comment by prashast** [comment]
Hi, sorry for not seeing this earlier and for testing our framework out!

I looked into this specific lib that you're analyzing and initial analysis showed that when Crystallizer tried to find any `toString` entrypoints it didn't find any causing an unusable gadget graph to be created. I've pushed a fix where the default  set of entrypoints considered included all other common entrypoints as well. This helped moved the analysis further by actually finding some usable entrypoints allowing a usable gadget graph to be created.
[EDIT]  Since this fix is not reflected in the docker image currently please just make this change inside the docker image: https://github.com/HexHive/Crystallizer/commit/c334560a439d335d1c479daae9a4f7e0844da5c5

A couple of recommendations thusing the `run_campaigns.sh` script, I would recommend running dynamic sink ID for at least 10 minutes. You can do it by passing `10m` as the argument to this  script. Also, I would recommend running steps until the dynamic sink ID first to ensure that viable sinks are identified (https://github.com/HexHive/Crystallizer/blob/main/eval/run_campaigns.sh#L6-L34). 

Please try these steps first and let me know if you have any further questions! :)
